# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fab7ddb56662a66090d7594bb9a16707a2247c5f1bd939fd08620e370a6bc8e73efbb3ded0b7ead0707bf1d12bed8fe5b87ea8197659642d3ecfd902b660884

test:
  secret_key_base: cecfd1afa46c656b3e4e1251ecfb8d2554f0aed1be5bc8a1e6bf773e37ea306595774ef653c098e0943b624f8709a124cae1b53ed0c3969d10efe24830a5b59d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
